version: '3.7'

services:
  mongodb:
    image: zcube/bitnami-compat-mongodb
    restart: always
    container_name: mongodb
    build: ./mongodb_replica
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=127.0.0.1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USER=anyuser
      - MONGODB_ROOT_PASSWORD=anypassword
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - 27017:27017
    volumes:
      - crud_mongodb_data:/bitnami/mongodb
 
  redis:
    image: bitnami/redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    volumes:
      - 'crud_redis_data:/bitnami/redis/data'

volumes:
  crud_mongodb_data:
  crud_redis_data:
